services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_NAME: "${APP_NAME}"
      APP_ENV: production
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "false"
      APP_URL: "${APP_URL}"
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: root
      DB_PASSWORD: "${DB_PASSWORD}"
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
    depends_on:
      - mysql
    networks:
      - laravel-network
      - coolify

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./:/var/www/html:ro
    depends_on:
      - app
    networks:
      - laravel-network
      - coolify
    labels:
      - traefik.enable=true
      - traefik.http.routers.portal-nginx.rule=Host(`data.anbksulteng.web.id`)
      - traefik.http.routers.portal-nginx.entrypoints=http,https
      - traefik.http.routers.portal-nginx.tls=true
      - traefik.http.routers.portal-nginx.tls.certresolver=letsencrypt
      - traefik.http.services.portal-nginx.loadbalancer.server.port=80

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
  coolify:
    external: true

volumes:
  mysql-data:
    driver: local
