services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        environment:
            APP_NAME: ${APP_NAME}
            APP_ENV: production
            APP_KEY: ${APP_KEY}
            APP_DEBUG: false
            APP_URL: ${APP_URL}

            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

            SESSION_DRIVER: database
            CACHE_STORE: database
            QUEUE_CONNECTION: database
        depends_on:
            - mysql
        networks:
            - laravel-network

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/app.conf
        depends_on:
            - app
        networks:
            - laravel-network

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel-network

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-queue
        restart: unless-stopped
        working_dir: /var/www/html
        command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
        volumes:
            - ./:/var/www/html
        environment:
            APP_ENV: production
            APP_URL: ${APP_URL}
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mysql
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local

