# Docker Compose untuk Dokploy
# Gunakan file ini jika deploy dengan docker-compose di Dokploy
# Atau gunakan Dockerfile.dokploy langsung untuk single container deployment

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dokploy
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      APP_NAME: "${APP_NAME:-Portal Data}"
      APP_ENV: production
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "false"
      APP_URL: "${APP_URL}"
      DB_CONNECTION: mysql
      DB_HOST: "${DB_HOST:-mysql}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME:-root}"
      DB_PASSWORD: "${DB_PASSWORD}"
      CACHE_STORE: database
      SESSION_DRIVER: database
      QUEUE_CONNECTION: database
      TURNSTILE_SITE_KEY: "${TURNSTILE_SITE_KEY}"
      TURNSTILE_SECRET_KEY: "${TURNSTILE_SECRET_KEY}"
    volumes:
      - app-storage:/var/www/html/storage
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dokploy-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  dokploy-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  app-storage:
    driver: local
